fix
net.minecraft.util.ResourceLocationException: Non [a-z0-9/._-] character in path of location: minecraft:343Industries/reference_plasma_pistol

because 343Industries is not a valid java identifier